# Generated by Django 5.2.5 on 2025-08-23 21:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_acidity', models.FloatField(verbose_name='Acidez Fija (g/L)')),
                ('volatile_acidity', models.FloatField(verbose_name='Acidez Volátil (g/L)')),
                ('citric_acid', models.FloatField(verbose_name='Ácido Cítrico (g/L)')),
                ('residual_sugar', models.FloatField(verbose_name='Azúcar Residual (g/L)')),
                ('chlorides', models.FloatField(verbose_name='Cloruros (g/L)')),
                ('free_sulfur_dioxide', models.FloatField(verbose_name='Dióxido de Azufre Libre (mg/L)')),
                ('total_sulfur_dioxide', models.FloatField(verbose_name='Dióxido de Azufre Total (mg/L)')),
                ('density', models.FloatField(verbose_name='Densidad (g/cm³)')),
                ('ph', models.FloatField(verbose_name='pH')),
                ('sulphates', models.FloatField(verbose_name='Sulfatos (g/L)')),
                ('alcohol', models.FloatField(verbose_name='Alcohol (% vol)')),
                ('quality', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10, verbose_name='Calidad')),
                ('confidence', models.FloatField(verbose_name='Confianza (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Análisis de Vino',
                'verbose_name_plural': 'Análisis de Vinos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WineClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.CharField(choices=[('sugar', 'Por Contenido de Azúcar'), ('bubbles', 'Por Burbujas'), ('fortified', 'Fortificado/Generoso'), ('dessert', 'De Postre')], max_length=20, verbose_name='Tipo de Clasificación')),
                ('classification_name', models.CharField(max_length=100, verbose_name='Nombre de Clasificación')),
                ('confidence', models.FloatField(verbose_name='Confianza (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='api.wineanalysis')),
            ],
            options={
                'verbose_name': 'Clasificación de Vino',
                'verbose_name_plural': 'Clasificaciones de Vinos',
            },
        ),
        migrations.CreateModel(
            name='WineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=50, verbose_name='Nombre del Componente')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Porcentaje del Total')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='api.wineanalysis')),
            ],
            options={
                'verbose_name': 'Componente del Vino',
                'verbose_name_plural': 'Componentes del Vino',
            },
        ),
    ]
