# Generated by Django 5.2.4 on 2025-08-24 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDropoutAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('family_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingresos Familiares')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('economic_situation', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10, verbose_name='Situación Económica')),
                ('study_time', models.IntegerField(verbose_name='Horas de Estudio por Semana')),
                ('school_support', models.BooleanField(default=False, verbose_name='Apoyo Educativo de la Escuela')),
                ('family_support', models.BooleanField(default=False, verbose_name='Apoyo Familiar')),
                ('extra_educational_support', models.BooleanField(default=False, verbose_name='Clases Particulares')),
                ('risk_level', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10, verbose_name='Nivel de Riesgo')),
                ('confidence', models.FloatField(verbose_name='Confianza (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Análisis de Abandono Escolar',
                'verbose_name_plural': 'Análisis de Abandono Escolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
