# Generated by Django 5.2.4 on 2025-08-24 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentdropoutanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdropoutanalysis',
            name='analysis_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Análisis'),
        ),
        migrations.AddField(
            model_name='studentdropoutanalysis',
            name='attendance',
            field=models.BooleanField(default=True, verbose_name='Asistencia Regular'),
        ),
    ]
